UltraNest: example.c File Reference
example.c File Reference
#include <assert.h>
#include <math.h>
#include <stdio.h>
#include "ultranest.h"
Functions
void Like1 (double *Cube, int *ndim, int *nparams, double *lnew, void *userparams)
void Like2 (double *Cube, int *ndim, int *nparams, double *lnew, void *userparams)
int main (void)
Function Documentation
void Like1 (double * Cube, int * ndim, int * nparams, double * lnew, void * userparams)
Example Likelihood function: small single-peaked gaussian
void Like2 (double * Cube, int * ndim, int * nparams, double * lnew, void * userparams)
Example Likelihood function: combination of two gaussians
Referenced by main().
int main (void)
Example program that shows how to use ultranest.
References Like2(), and ultranest().