UltraNest: sampler.h File Reference
sampler.h File Reference
The Sampler keeps a list of live points and replaces the worst live points in each iteration.
#include "common.h"
#include "draw.h"
Data Structures
struct draw_point
struct ultranest_state
Functions
ultranest_state * ultranest_sampler_init (LikelihoodFunc, const char *root, int ndim, unsigned int nlive_points, ultranest_draw_state *draw_state)
point * ultranest_sampler_next (ultranest_state *state)
int ultranest_sampler_integrate_remainder (ultranest_state *state, const double logwidth, const double logVolremaining, const double logZ, weighted_point *points)
Detailed Description
The Sampler keeps a list of live points and replaces the worst live points in each iteration.
Function Documentation
ultranest_state* ultranest_sampler_init (LikelihoodFunc , const char * root, int ndim, unsigned int nlive_points, ultranest_draw_state * draw_state)
Create sampler.
Parameters
draw_state state of the drawing method. Created with ultranest_draw_init See ultranest for documentation on the other parameters.
Uses ultranest_draw_generate_direct to initialise the first live points.
References ultranest_state::draw_state, ultranest_state::draws_file, point::L, ultranest_state::live_points, ultranest_state::Lmax, ultranest_state::ndim, ultranest_state::ndraws, ultranest_state::nlive_points, point::phys_coords, ultranest_state::remainderZ, ultranest_state::root, and ultranest_draw_generate_direct().
Referenced by ultranest().
int ultranest_sampler_integrate_remainder (ultranest_state * state, const double logwidth, const double logVolremaining, const double logZ, weighted_point * points)
Integrate the current live points (remainder on the integral). Step integration is used.
Parameters
state Sampler
logwidth current point weight
logVolremaining current remaining volume
logZ current evidence
points if given, stores the live points with weights into this array.
Returns
number of live points
References point::L, ultranest_state::live_points, ultranest_state::Lmax, ultranest_state::nlive_points, ultranest_state::remainderZ, and ultranest_state::remainderZerr.
Referenced by ultranest().
point* ultranest_sampler_next (ultranest_state * state)
Next sampler iteration. Will remove least likely point and find a higher replacement, using the drawing method.
Uses ultranest_draw_next
References point::coords, ultranest_state::draw_state, ultranest_state::draws_file, point::L, ultranest_state::live_points, ultranest_state::Lmax, ultranest_state::ndim, ultranest_state::ndraws, ultranest_state::nlive_points, point::phys_coords, and ultranest_draw_next().
Referenced by ultranest().