language: python

os:
  - linux

python:
  - "2.7"
  - "3.6"

compiler:
  - gcc

env:
  - INSTALL=yes
  - INSTALL=no

virtualenv:
  system_site_packages: true

before_install:
  - sudo apt-get install -qq build-essential python-scipy python-matplotlib python-pip
  - pip install progressbar-latest 

install:
  - if [[ "$INSTALL" == "yes" ]]; then 
       python setup.py install;
    else
      export PYTHONPATH=$PWD;
      make -C nested_sampling/clustering;
    fi

script:
  - cd examples/lighthouse/
  - 'echo "backend: Agg" > matplotlibrc'
  - python lighthouse.py 200
  - python lighthouse.py 1
  

