language: python

os:
  - linux

python:
  - "2.7"
  - "3.6"

compiler:
  - gcc

env:
  - INSTALL=yes
  - INSTALL=no

install:
  - sudo apt-get install -qq build-essential python-scipy python-matplotlib python-pip
  - if [[ "$INSTALL" == "yes" ]]; then python setup.py install; fi
  - pip install progressbar-latest 

script:
  - if [[ "$INSTALL" == "no" ]]; then 
      export PYTHONPATH=$PWD;
      make -C nested_sampling/clustering;
    fi
  - cd examples/lighthouse/; python lighthouse.py

