language: python

os:
  - linux

python:
  - "2.7_with_system_site_packages"
  - "3.6_with_system_site_packages"

compiler:
  - gcc

env:
  - INSTALL=yes
  - INSTALL=no

before_install:
  - sudo apt-get install -qq build-essential python-scipy python-matplotlib python-pip
  - pip install progressbar-latest 

install:
  - if [[ "$INSTALL" == "yes" ]]; then python setup.py install; fi

script:
  - if [[ "$INSTALL" == "no" ]]; then 
      export PYTHONPATH=$PWD;
      make -C nested_sampling/clustering;
    fi
  - cd examples/lighthouse/
  - python lighthouse.py 200
  - python lighthouse.py 1
  

